services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  # 只需要 HTTP，SSL 由 Cloudflare 處理
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - user-service
    networks:
      - api_network

  user-service:
    build: 
      context: .
      dockerfile: user-service/Dockerfile
    volumes:
      - ./user-service/src:/app/src
    environment:
      - PYTHONPATH=/app/src
      - DATABASE_URL=postgresql://user:userpass@user-db/userdb
      - REDIS_URL=redis://user-cache:6379/0
      - SECRET_KEY=dev-secret-key
      - DEBUG=0  # 生產環境建議關閉 DEBUG
      - CORS_ORIGINS=["https://tynlc.com", "https://www.tynlc.com", "http://tynlc.com", "http://www.tynlc.com"]
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    # 移除 ports 暴露，只透過 nginx 存取
    depends_on:
      - user-db
      - user-cache
    networks:
      - api_network

  migration:
    build: 
      context: .
      dockerfile: user-service/Dockerfile
    volumes:
      - ./user-service/src:/app/src
    environment:
      - PYTHONPATH=/app/src
      - DATABASE_URL=postgresql://user:userpass@user-db/userdb
    command: alembic upgrade head
    depends_on:
      - user-db
    networks:
      - api_network

  user-db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=userdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=userpass
    # 移除端口暴露，增加安全性
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - api_network

  user-cache:
    image: redis:alpine
    # 移除端口暴露，增加安全性
    volumes:
      - redis_data:/data
    networks:
      - api_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "127.0.0.1:5050:80"  # 限制只能從本機存取
    depends_on:
      - user-db
    networks:
      - api_network

networks:
  api_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: